export const SPECIALTIES = [
  {
    id: 'tim-mach',
    name: 'Tim Mạch',
    code: 'CARDIO',
    description: 'Chẩn đoán và điều trị bệnh lý tăng huyết áp, mạch vành, rối loạn nhịp tim',
    iconName: 'HeartPulse',
    doctorCount: 3,
    color: 'from-rose-500 to-red-600',
    bgColor: 'bg-rose-50 text-rose-600 border-rose-200'
  },
  {
    id: 'da-lieu',
    name: 'Da Liễu',
    code: 'DERMA',
    description: 'Điều trị viêm da cơ địa, mụn trứng cá, nám sạm và thẩm mỹ da liễu',
    iconName: 'Sparkles',
    doctorCount: 2,
    color: 'from-pink-500 to-rose-500',
    bgColor: 'bg-pink-50 text-pink-600 border-pink-200'
  },
  {
    id: 'nhi-khoa',
    name: 'Nhi Khoa',
    code: 'PEDI',
    description: 'Chăm sóc sức khỏe toàn diện, tiêm chủng và dinh dưỡng cho trẻ từ sơ sinh',
    iconName: 'Baby',
    doctorCount: 2,
    color: 'from-amber-500 to-orange-500',
    bgColor: 'bg-amber-50 text-amber-600 border-amber-200'
  },
  {
    id: 'co-xuong-khop',
    name: 'Cơ Xương Khớp',
    code: 'ORTHO',
    description: 'Khám thoái hóa khớp, thoát vị đĩa đệm, loãng xương và vật lý trị liệu',
    iconName: 'Activity',
    doctorCount: 2,
    color: 'from-emerald-500 to-teal-600',
    bgColor: 'bg-emerald-50 text-emerald-600 border-emerald-200'
  },
  {
    id: 'than-kinh',
    name: 'Thần Kinh',
    code: 'NEURO',
    description: 'Điều trị đau đầu mãn tính, rối loạn giấc ngủ, tiền đình và tai biến mạch máu não',
    iconName: 'Brain',
    doctorCount: 2,
    color: 'from-indigo-500 to-purple-600',
    bgColor: 'bg-indigo-50 text-indigo-600 border-indigo-200'
  },
  {
    id: 'mat',
    name: 'Mắt',
    code: 'OPHTHA',
    description: 'Khám tật khúc xạ, đo thị lực, đục thủy tinh thể và các bệnh giác mạc',
    iconName: 'Eye',
    doctorCount: 1,
    color: 'from-cyan-500 to-blue-600',
    bgColor: 'bg-cyan-50 text-cyan-600 border-cyan-200'
  },
  {
    id: 'tai-mui-hong',
    name: 'Tai Mũi Họng',
    code: 'ENT',
    description: 'Nội soi tai mũi họng, viêm xoang, viêm amidan, polyp mũi và thính lực',
    iconName: 'Ear',
    doctorCount: 2,
    color: 'from-teal-500 to-cyan-600',
    bgColor: 'bg-teal-50 text-teal-600 border-teal-200'
  },
  {
    id: 'rang-ham-mat',
    name: 'Răng Hàm Mặt',
    code: 'DENTAL',
    description: 'Chăm sóc nha khoa, cạo vôi, niềng răng thẩm mỹ và cấy ghép Implant',
    iconName: 'Smile',
    doctorCount: 2,
    color: 'from-sky-500 to-blue-600',
    bgColor: 'bg-sky-50 text-sky-600 border-sky-200'
  }
];

export const DOCTORS = [
  {
    id: 'doc-1',
    name: 'PGS.TS.BS Trần Minh Đức',
    specialtyId: 'tim-mach',
    specialtyName: 'Tim Mạch',
    title: 'Phó Giáo Sư, Tiến Sĩ, Bác Sĩ CKI',
    experienceYears: 24,
    rating: 4.9,
    reviewCount: 382,
    consultationFee: 500000,
    hospital: 'Bệnh viện Tim Tâm Đức - Phòng khám MediBook',
    address: '215 Hồng Bàng, Phường 11, Quận 5, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
    bio: 'Chuyên gia đầu ngành về can thiệp tim mạch, điều trị suy tim và xơ vữa động mạch với hơn 24 năm cống hiến y học.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'],
    badges: ['Bác sĩ nổi bật', 'Chuyên gia đầu ngành']
  },
  {
    id: 'doc-2',
    name: 'BSCKII Lê Phương Thảo',
    specialtyId: 'da-lieu',
    specialtyName: 'Da Liễu',
    title: 'Bác Sĩ Chuyên Khoa II Da Liễu',
    experienceYears: 16,
    rating: 4.85,
    reviewCount: 295,
    consultationFee: 350000,
    hospital: 'Bệnh viện Da Liễu TP.HCM',
    address: '68 Nguyễn Thông, Phường Võ Thị Sáu, Quận 3, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1594824813583-097f482d8c30?auto=format&fit=crop&w=600&q=80',
    bio: 'Nhiều năm kinh nghiệm điều trị thẩm mỹ da công nghệ cao, phục hồi sẹo rỗ, trị mụn dứt điểm và trẻ hóa da.',
    workingDays: ['Thứ 2', 'Thứ 4', 'Thứ 6', 'Chủ Nhật'],
    badges: ['Tận tâm', 'Đặt hẹn nhiều nhất']
  },
  {
    id: 'doc-3',
    name: 'ThS.BS Nguyễn Hoàng Nam',
    specialtyId: 'nhi-khoa',
    specialtyName: 'Nhi Khoa',
    title: 'Thạc Sĩ, Bác Sĩ Nhi Khoa',
    experienceYears: 12,
    rating: 4.95,
    reviewCount: 420,
    consultationFee: 300000,
    hospital: 'Bệnh viện Nhi Đồng 1',
    address: '341 Sư Vạn Hạnh, Phường 10, Quận 10, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80',
    bio: 'Bác sĩ thân thiện, giàu lòng kiên nhẫn, chuyên chẩn đoán các bệnh đường hô hấp, tiêu hóa và tư vấn phát triển chiều cao cho trẻ.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 5', 'Thứ 6', 'Thứ 7'],
    badges: ['Được phụ huynh tin chọn', 'Nhiệt huyết']
  },
  {
    id: 'doc-4',
    name: 'BSCKI Đặng Quốc Huy',
    specialtyId: 'co-xuong-khop',
    specialtyName: 'Cơ Xương Khớp',
    title: 'Bác Sĩ CKI Chấn Thương Chỉnh Hình',
    experienceYears: 15,
    rating: 4.8,
    reviewCount: 210,
    consultationFee: 400000,
    hospital: 'Bệnh viện Chấn Thương Chỉnh Hình TP.HCM',
    address: '929 Trần Hưng Đạo, Phường 1, Quận 5, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=600&q=80',
    bio: 'Chuyên gia phục hồi chức năng sau chấn thương thể thao, tiêm khớp nội soi không đau và điều trị thoái hóa cột sống.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 7'],
    badges: ['Phục hồi nhanh']
  },
  {
    id: 'doc-5',
    name: 'TS.BS Phan Thanh Hằng',
    specialtyId: 'than-kinh',
    specialtyName: 'Thần Kinh',
    title: 'Tiến Sĩ Bác Sĩ Nội Thần Kinh',
    experienceYears: 18,
    rating: 4.92,
    reviewCount: 312,
    consultationFee: 450000,
    hospital: 'Bệnh viện Chợ Rẫy',
    address: '201B Nguyễn Chí Thanh, Phường 12, Quận 5, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80',
    bio: 'Có nhiều đề tài nghiên cứu quốc tế về chứng đau nửa đầu Migraine, rối loạn lo âu suy nhược thần kinh và hội chứng mất ngủ.',
    workingDays: ['Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'],
    badges: ['Chuyên gia giấc ngủ']
  },
  {
    id: 'doc-6',
    name: 'ThS.BSCKI Vũ Đình Trí',
    specialtyId: 'tai-mui-hong',
    specialtyName: 'Tai Mũi Họng',
    title: 'Thạc Sĩ Bác Sĩ Tai Mũi Họng',
    experienceYears: 14,
    rating: 4.88,
    reviewCount: 245,
    consultationFee: 350000,
    hospital: 'Bệnh viện Tai Mũi Họng TP.HCM',
    address: '155B Trần Quốc Thảo, Phường 9, Quận 3, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80',
    bio: 'Áp dụng công nghệ nội soi ống mềm không gây khó chịu, điều trị viêm amidan hốc mủ, vẹo vách ngăn và khàn tiếng kéo dài.',
    workingDays: ['Thứ 2', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'],
    badges: ['Nội soi êm ái']
  },
  {
    id: 'doc-7',
    name: 'BSCKII Phạm Ngọc Bích',
    specialtyId: 'mat',
    specialtyName: 'Mắt',
    title: 'Bác Sĩ CKI Mắt - Khúc Xạ Nhãn Khoa',
    experienceYears: 17,
    rating: 4.89,
    reviewCount: 189,
    consultationFee: 350000,
    hospital: 'Bệnh viện Mắt TP.HCM',
    address: '280 Điện Biên Phủ, Phường Võ Thị Sáu, Quận 3, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=600&q=80',
    bio: 'Chuyên gia mổ cận thị SMILE/FemtoLasik, điều trị khô mắt do màn hình máy tính và chẩn đoán sớm tăng nhãn áp.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 5', 'Thứ 7'],
    badges: ['Nhẹ nhàng chu đáo']
  },
  {
    id: 'doc-8',
    name: 'Bác Sĩ CKI Đỗ Bảo Long',
    specialtyId: 'rang-ham-mat',
    specialtyName: 'Răng Hàm Mặt',
    title: 'Bác Sĩ CKI Nha Khoa Thẩm Mỹ',
    experienceYears: 11,
    rating: 4.91,
    reviewCount: 260,
    consultationFee: 300000,
    hospital: 'Bệnh viện Răng Hàm Mặt Trung Ương',
    address: '201A Nguyễn Chí Thanh, Phường 12, Quận 5, TP.HCM',
    avatar: 'https://images.unsplash.com/photo-1629425733761-caae3b5f2e50?auto=format&fit=crop&w=600&q=80',
    bio: 'Bác sĩ trẻ năng động với chứng chỉ chỉnh nha Invisalign Hoa Kỳ, dán sứ Veneer thẩm mỹ bảo tồn răng thật tối đa.',
    workingDays: ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 6', 'Thứ 7'],
    badges: ['Nha khoa không đau']
  }
];

export const TIME_SLOTS = [
  { id: 't1', time: '08:00 - 08:30', session: 'morning' },
  { id: 't2', time: '08:30 - 09:00', session: 'morning' },
  { id: 't3', time: '09:00 - 09:30', session: 'morning' },
  { id: 't4', time: '09:30 - 10:00', session: 'morning' },
  { id: 't5', time: '10:00 - 10:30', session: 'morning' },
  { id: 't6', time: '10:30 - 11:00', session: 'morning' },
  { id: 't7', time: '13:30 - 14:00', session: 'afternoon' },
  { id: 't8', time: '14:00 - 14:30', session: 'afternoon' },
  { id: 't9', time: '14:30 - 15:00', session: 'afternoon' },
  { id: 't10', time: '15:00 - 15:30', session: 'afternoon' },
  { id: 't11', time: '15:30 - 16:00', session: 'afternoon' },
  { id: 't12', time: '16:00 - 16:30', session: 'afternoon' }
];

export const INITIAL_APPOINTMENTS = [
  {
    id: 'MDB-2026-8812',
    patientName: 'Nguyễn Văn An',
    patientPhone: '0912345678',
    patientEmail: 'vanan.nguyen@gmail.com',
    patientDob: '1990-05-14',
    patientGender: 'Nam',
    patientAddress: 'Quận 7, TP.HCM',
    doctorId: 'doc-1',
    doctorName: 'PGS.TS.BS Trần Minh Đức',
    specialtyName: 'Tim Mạch',
    consultationFee: 500000,
    appointmentDate: '2026-09-29',
    timeSlot: '08:30 - 09:00',
    symptoms: 'Thường xuyên hồi hộp, tức ngực trái khi vận động nhẹ, huyết áp dao động.',
    status: 'pending', // pending, confirmed, completed, cancelled
    createdAt: '2026-09-27T08:15:00.000Z',
    notes: 'Bệnh nhân mang theo kết quả điện tim gần nhất'
  },
  {
    id: 'MDB-2026-7341',
    patientName: 'Trần Thị Mai',
    patientPhone: '0987654321',
    patientEmail: 'maitran.94@gmail.com',
    patientDob: '1994-11-20',
    patientGender: 'Nữ',
    patientAddress: 'Quận Bình Thạnh, TP.HCM',
    doctorId: 'doc-2',
    doctorName: 'BSCKII Lê Phương Thảo',
    specialtyName: 'Da Liễu',
    consultationFee: 350000,
    appointmentDate: '2026-09-28',
    timeSlot: '14:00 - 14:30',
    symptoms: 'Da mặt nổi mẩn đỏ, ngứa ngáy sau khi đổi kem dưỡng ẩm 3 ngày trước.',
    status: 'confirmed',
    createdAt: '2026-09-26T14:20:00.000Z',
    notes: 'Đã gọi điện xác nhận lịch hẹn'
  },
  {
    id: 'MDB-2026-9043',
    patientName: 'Lê Hoàng Nam (Bé Lê Minh Khôi)',
    patientPhone: '0905123456',
    patientEmail: 'nam.lehoang@yahoo.com',
    patientDob: '2022-03-10',
    patientGender: 'Nam',
    patientAddress: 'Thành phố Thủ Đức, TP.HCM',
    doctorId: 'doc-3',
    doctorName: 'ThS.BS Nguyễn Hoàng Nam',
    specialtyName: 'Nhi Khoa',
    consultationFee: 300000,
    appointmentDate: '2026-09-30',
    timeSlot: '09:30 - 10:00',
    symptoms: 'Bé ho đờm về đêm, sốt nhẹ 38 độ, biếng ăn 2 ngày nay.',
    status: 'pending',
    createdAt: '2026-09-27T09:40:00.000Z',
    notes: 'Ưu tiên khám nhi'
  },
  {
    id: 'MDB-2026-6129',
    patientName: 'Phạm Thu Hương',
    patientPhone: '0938889999',
    patientEmail: 'thuhuong.pham@outlook.com',
    patientDob: '1985-08-15',
    patientGender: 'Nữ',
    patientAddress: 'Quận 1, TP.HCM',
    doctorId: 'doc-4',
    doctorName: 'BSCKI Đặng Quốc Huy',
    specialtyName: 'Cơ Xương Khớp',
    consultationFee: 400000,
    appointmentDate: '2026-09-25',
    timeSlot: '10:00 - 10:30',
    symptoms: 'Đau mỏi cổ vai gáy, tê lan xuống ngón tay phải do ngồi văn phòng nhiều.',
    status: 'completed',
    createdAt: '2026-09-24T11:00:00.000Z',
    notes: 'Đã hoàn thành khám, kê đơn thuốc và hướng dẫn bài tập vật lý trị liệu.'
  },
  {
    id: 'MDB-2026-5520',
    patientName: 'Đỗ Minh Khang',
    patientPhone: '0971239876',
    patientEmail: 'khangdo.tech@gmail.com',
    patientDob: '1998-02-18',
    patientGender: 'Nam',
    patientAddress: 'Quận Tân Bình, TP.HCM',
    doctorId: 'doc-5',
    doctorName: 'TS.BS Phan Thanh Hằng',
    specialtyName: 'Thần Kinh',
    consultationFee: 450000,
    appointmentDate: '2026-09-27',
    timeSlot: '15:00 - 15:30',
    symptoms: 'Mất ngủ kéo dài, căng thẳng làm việc quá độ, hay chóng mặt khi đứng dậy.',
    status: 'cancelled',
    cancellationReason: 'Bệnh nhân bận công tác đột xuất vào ngày khám.',
    createdAt: '2026-09-25T16:30:00.000Z',
    notes: 'Đã hủy theo yêu cầu bệnh nhân'
  },
  {
    id: 'MDB-2026-4418',
    patientName: 'Vũ Tuấn Anh',
    patientPhone: '0945678123',
    patientEmail: 'tuananh.vu@gmail.com',
    patientDob: '2001-09-12',
    patientGender: 'Nam',
    patientAddress: 'Quận 10, TP.HCM',
    doctorId: 'doc-8',
    doctorName: 'Bác Sĩ CKI Đỗ Bảo Long',
    specialtyName: 'Răng Hàm Mặt',
    consultationFee: 300000,
    appointmentDate: '2026-09-28',
    timeSlot: '09:00 - 09:30',
    symptoms: 'Đau nhức vùng răng số 8 hàm dưới bên phải, nướu hơi sưng đỏ.',
    status: 'confirmed',
    createdAt: '2026-09-27T07:10:00.000Z',
    notes: 'Khám nhổ răng khôn'
  }
];
